// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8P8qEFBUc2WogGDvPoGOcf2fP2E6ksCo',
    appId: '1:132880077543:web:42757b02d5e07be7450842',
    messagingSenderId: '132880077543',
    projectId: 'taniku-a66e2',
    authDomain: 'taniku-a66e2.firebaseapp.com',
    storageBucket: 'taniku-a66e2.firebasestorage.app',
    measurementId: 'G-V2SQRHL62W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKQxLk2sQXS1dyqg1_6dOUzF7h1lgkZXQ',
    appId: '1:132880077543:android:e31a5830fe71a580450842',
    messagingSenderId: '132880077543',
    projectId: 'taniku-a66e2',
    storageBucket: 'taniku-a66e2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8P8qEFBUc2WogGDvPoGOcf2fP2E6ksCo',
    appId: '1:132880077543:web:4ecdb5a7271c1609450842',
    messagingSenderId: '132880077543',
    projectId: 'taniku-a66e2',
    authDomain: 'taniku-a66e2.firebaseapp.com',
    storageBucket: 'taniku-a66e2.firebasestorage.app',
    measurementId: 'G-F8KGPXNTKV',
  );

}